### ISSUE TITLE
Search inside base DN recursively

### ISSUE THREAD

**Issue by gentunian** [Alaneor/AD-X#10]
I've done a search with the `Task` object. It seems that the search is done in the same level of that `DN`. In my case, we have `OU`s inside another `OU`s, for example, IT Deparment could be a `OU` that holds Development and Operations `OU`s.

The search is being done at the level of IT Deparment instead of its subtree. Doc is rather sparse so maybe I'm missing something. Now I'm reading the code at the time I'm filling this question (I can't label the issue as question)

Best regards

**Comment by gentunian** [comment]
Oh god... nevermind, I left the `Enum\Operation::OpList` from a previous modification.

My bad

**Comment by Alaneor** [comment]
Hi, no problem - glad you made it work!

By the way, if you have some ideas about improving the docs I always welcome a pull request.:)

**Comment by gentunian** [comment]
I found that it was necessary and not optional to create the schema cache. Otherwise, you will get `Operations error` while making a search with `Task` object. At least that was my case with my AD.

I'll look forward to keep that on mind. Is the better ldap AD abstraction I found so far!
