### ISSUE TITLE
SSL/LDAPS

### ISSUE THREAD

**Issue by jamenlang** [Alaneor/AD-X#11]
I see that tutorials are a future plan, could you provide a tutorial on configuring SSL/LDAPS on server 2012? I can telnet to port 636 on the AD server however AD-X says that it failed to connect with no further indication of what the problem is, but port 389 works fine.

Does the certificate file need to be imported before LDAPS works or is the server side certificate trusted automatically?

**Comment by Alaneor** [comment]
Unfortunately I never got ldaps to work back in the day. I believe the problem was that the AD server's certificate was not trusted because it was self-signed or some such issue.

Ultimately I switched to TLS with disabled certificate verification. Sorry that I cannot be of much help in this case.
